apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJpZGtkZXZvcHMuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIlpHOWphMlZ5WTNKbFpEcFRZV2x1YVd0QU1qST0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
